spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gitnx}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  thymeleaf:
    cache: true

server:
  port: 9090
  forward-headers-strategy: native

gitnx:
  repos:
    base-path: ${GITNX_REPOS_PATH:/opt/gitnx/repos}
  clone:
    http-base-url: ${GITNX_CLONE_URL:https://git.ultari.co.kr/repo}

workbench:
  datasource:
    url: ${WB_DB_URL:jdbc:mariadb://10.0.0.177:7706/WB_ORGANIZATION}
    username: ${WB_DB_USERNAME:root}
    password: ${WB_DB_PASSWORD:ultari12#$}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    com.gitnx: INFO
    org.eclipse.jgit: WARN
