
spring:
  application:
    name: gitnx

  datasource:
    url: jdbc:postgresql://localhost:5432/gitnx
    username: root
    password: "ultari12#$"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8082
  servlet:
    session:
      timeout: 30m

gitnx:
  repos:
    base-path: ${user.home}/gitnx-repos
  clone:
    http-base-url: http://125.131.105.208:8082/repo

logging:
  level:
    com.gitnx: DEBUG
    org.eclipse.jgit: INFO
